<?php
ob_start();
session_start();
$PASSWORD='Sourav@2026!'; // Change this before publishing.
$uploadDir=__DIR__.'/uploads/';
if(!is_dir($uploadDir)) mkdir($uploadDir,0755,true);
function clean($s){return htmlspecialchars($s,ENT_QUOTES,'UTF-8');}
if(isset($_POST['login'])){if(hash_equals($GLOBALS['PASSWORD'],$_POST['password']??'')){$_SESSION['admin']=true;}else{$error='Incorrect password.';}}
if(isset($_GET['logout'])){session_destroy();header('Location: admin.php');exit;}
if(empty($_SESSION['admin'])): ?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Login</title><style>body{font-family:system-ui;background:#f7f9fc;display:grid;place-items:center;min-height:100vh}.box{background:#fff;padding:30px;border-radius:18px;box-shadow:0 15px 50px #0001;width:min(380px,90%)}input,button{width:100%;padding:12px;margin-top:10px;border-radius:10px;border:1px solid #ddd;font:inherit}button{background:#152033;color:#fff;font-weight:800;cursor:pointer}.err{color:#c00;font-size:14px}</style></head><body><div class="box"><h2>Portfolio Admin</h2><p>Login to manage your portfolio files.</p><?php if(!empty($error)): ?><div class="err"><?php echo clean($error); ?></div><?php endif; ?><form method="post"><input type="password" name="password" placeholder="Admin password" required><button name="login">Login</button></form></div></body></html><?php exit; endif;
function uploadSlot($field,$prefix,$allowed,$max=100000000){global $uploadDir;if(empty($_FILES[$field])||$_FILES[$field]['error']===UPLOAD_ERR_NO_FILE)return null;$f=$_FILES[$field];if($f['error']!==UPLOAD_ERR_OK)return 'Upload failed.';if($f['size']>$max)return 'File is too large.';$ext=strtolower(pathinfo($f['name'],PATHINFO_EXTENSION));if(!in_array($ext,$allowed,true))return 'Invalid file type.';foreach(glob($uploadDir.$prefix.'.*') as $old) @unlink($old);$target=$uploadDir.$prefix.'.'.$ext;return move_uploaded_file($f['tmp_name'],$target)?null:'Could not save file.';}
$msg='';$err='';
if(isset($_POST['save'])){$kind=$_POST['kind']??'';$slot=(int)($_POST['slot']??0);$map=['video'=>[1,14,['mp4','webm','mov','m4v']],'thumb'=>[1,4,['jpg','jpeg','png','webp']],'poster'=>[1,5,['jpg','jpeg','png','webp']]];if(isset($map[$kind])&&$slot>=$map[$kind][0]&&$slot<=$map[$kind][1]){$prefix=$kind.'_'.str_pad($slot,2,'0',STR_PAD_LEFT);$e=uploadSlot('asset',$prefix,$map[$kind][2]);if($e)$err=$e;else $msg=ucfirst($kind).' '.$slot.' uploaded successfully.';}else{$err='Invalid slot.';}}
if(isset($_POST['profile'])){$e=uploadSlot('profile','profile',['jpg','jpeg','png','webp']);if($e)$err=$e;else $msg='Profile photo updated.';}
if(isset($_POST['delete'])){$file=basename($_POST['file']??'');if(preg_match('/^(video|thumb|poster)_\d{2}\.[a-z0-9]+$/i',$file)||preg_match('/^profile\.[a-z0-9]+$/i',$file)){ @unlink($uploadDir.$file);$msg='File removed.';}}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Portfolio Admin</title><style>body{font-family:system-ui;background:#f7f9fc;color:#152033;margin:0}.wrap{width:min(900px,92%);margin:40px auto}.top{display:flex;justify-content:space-between;align-items:center;gap:15px}.box{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:22px;margin:18px 0;box-shadow:0 10px 30px #0000000a}.row{display:flex;gap:12px;flex-wrap:wrap;align-items:end}.field{flex:1;min-width:160px}label{display:block;font-size:13px;font-weight:800;margin-bottom:6px}select,input[type=file],button{width:100%;padding:11px;border:1px solid #d8dee8;border-radius:10px;font:inherit;background:#fff}button{background:#152033;color:#fff;font-weight:800;cursor:pointer}.danger{background:#b42318}.msg{padding:12px;border-radius:10px;background:#ecfdf3;color:#067647}.err{padding:12px;border-radius:10px;background:#fff1f2;color:#b42318}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.item{border:1px solid #e2e8f0;padding:12px;border-radius:12px}.item form{margin-top:8px}@media(max-width:600px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}</style></head><body><div class="wrap"><div class="top"><div><h1>Portfolio Admin</h1><p>Upload files that appear on the public portfolio.</p></div><a href="?logout=1">Logout</a></div><?php if($msg): ?><div class="msg"><?php echo clean($msg); ?></div><?php endif; ?><?php if($err): ?><div class="err"><?php echo clean($err); ?></div><?php endif; ?>
<div class="box"><h2>Profile Photo</h2><form method="post" enctype="multipart/form-data"><input type="file" name="profile" accept="image/*" required><button name="profile">Update Profile Photo</button></form></div>
<div class="box"><h2>Upload Portfolio Item</h2><form method="post" enctype="multipart/form-data"><div class="row"><div class="field"><label>Type</label><select name="kind" id="kind"><option value="video">Video</option><option value="thumb">Thumbnail</option><option value="poster">Poster</option></select></div><div class="field"><label>Slot</label><select name="slot" id="slot"></select></div><div class="field"><label>File</label><input type="file" name="asset" id="asset" required></div></div><button name="save">Upload / Replace</button></form></div>
<div class="box"><h2>Current Files</h2><div class="grid"><?php foreach(glob($uploadDir.'*') as $p): $f=basename($p); ?><div class="item"><strong><?php echo clean($f); ?></strong><form method="post" onsubmit="return confirm('Delete this file?')"><input type="hidden" name="file" value="<?php echo clean($f); ?>"><button class="danger" name="delete">Delete</button></form></div><?php endforeach; if(!glob($uploadDir.'*')): ?><p>No uploads yet.</p><?php endif; ?></div></div>
<p><a href="index.php">← View Public Portfolio</a></p></div><script>const kind=document.getElementById('kind'),slot=document.getElementById('slot'),asset=document.getElementById('asset');function fill(){let n=kind.value==='video'?14:kind.value==='thumb'?4:5;slot.innerHTML='';for(let i=1;i<=n;i++){let o=document.createElement('option');o.value=i;o.textContent=String(i).padStart(2,'0');slot.appendChild(o)}asset.accept=kind.value==='video'?'video/*':'image/*'}kind.onchange=fill;fill();</script></body></html>
